trying stuff

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -35,24 +35,29 @@ echo "-----> Using Erlang/OTP $ver"
 )
 
 echo "-------> Unpacking Erlang/OTP $ver"
+WORK_DIR=$(pwd)
 mkdir -p ${ERLROOT}
 if [ ! -d ${cache}/otp_release_${ver} ] ; then
-  WORK_DIR=$(pwd)
   mkdir /tmp/otp_build
   cd /tmp/otp_build
   tar zxf ${cache}/${tarball} --strip-components=1
   echo "-------> Building Erlang/OTP $ver"
   #export ERL_TOP=`pwd`
-  ./configure
+  ./configure 2>&1 | sed -u 's/^/       /'
   make 2>&1 | sed -u 's/^/       /'
   make RELEASE_ROOT=${ERLROOT} release 2>&1 | sed -u 's/^/       /'
   cp -a ${ERLROOT} ${cache}/otp_release_${ver}
-  cd $WORK_DIR
 else
   cp -a ${cache}/otp_release_${ver} ${ERLROOT}
 fi
 echo "-------> Installing Erlang/OTP $ver"
-${ERLROOT}/Install -minimal ${ERLROOT} 2>&1 | sed -u 's/^/       /'
+cd ${ERLROOT}
+./Install -minimal ${ERLROOT} 2>&1 | sed -u 's/^/       /'
+if [ ${PIPESTATUS[0]} -ne 0 ]; then
+  echo "-----> Build failed"
+  exit 1
+fi
+cd $WORK_DIR
 
 PATH=/app/otp/bin:$PATH
 export PATH
@@ -84,8 +89,7 @@ unset GIT_DIR
 PATH=$PATH:${cache}/bin/ make 2>&1 | sed -u 's/^/       /'
 if [ ${PIPESTATUS[0]} -ne 0 ]; then
   echo "-----> Build failed"
-  ls -l /app/otp/lib/
-  ls -l /app/otp/lib/snmp-4.25.0.1/
+  ls -l /app/otp/
   exit 1
 fi
 
