trying stuff

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,81 +1,77 @@
 #!/bin/bash
 
-##
-# usage: bin/compile <build-dir> <cache-dir>
+abort()
+{
+    if [ $? -ne 0 ]; then
+      echo "-----> Build failed"
+      exit 1
+    fi
+}
+
+trap 'abort' 0
 
 set -e
-bpdir=$(cd $(dirname $(dirname $0)); pwd)
-mkdir -p "$1" "$2"
-build=$(cd "$1/" && pwd)
-test -z ${build} && exit
-cache=$(cd "$2/" && pwd)
-test -z ${cache} && exit
-DEFAULT_OTP_VERSION="17.1"
-if [ -f ${build}/.preferred_otp_version ]; then
-    OTP_VERSION=$(cat ${build}/.preferred_otp_version)
-fi
-ver=${OTP_VERSION:=${DEFAULT_OTP_VERSION}}
 
-ERLROOT=${build}/otp
-PROFILE=${HOME}/.profile.d
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+BUILDPACK_DIR=$(dirname $0)/../
+
+ERLROOT=$(mktemp -d)
+
+PATH=$ERLROOT/bin:${CACHE_DIR}/bin:$PATH
+export PATH
+
+DEFAULT_OTP_VERSION="17.1"
+if [ ! -f ${BUILD_DIR}/.preferred_otp_version ] ; then
+  echo $DEFAULT_OTP_VERSION > ${BUILD_DIR}/.preferred_otp_version
+fi
+
+OTP_VERSION=${$(cat ${BUILD_DIR}/.preferred_otp_version):=${DEFAULT_OTP_VERSION}}
 
 if [ ! -d ${cache}/bin/ ] ; then
   mkdir -p ${cache}/bin
 fi
-
-PATH=$ERLROOT/bin:${cache}/bin:$PATH
-export PATH
-
-echo "-----> Installing Erlang/OTP $ver"
-if [ -e ${cache}/bin/kerl ] ; then
-  curl -s -o ${cache}/bin/kerl https://raw.githubusercontent.com/spawngrid/kerl/master/kerl 2>&1 | sed -u 's/^/       /'
-  chmod +x ${cache}/bin/kerl
-fi
-if [ ! -d ${cache}/kerl ] ; then
+if [ ! -d ${cache}/kerl/ ] ; then
   mkdir -p ${cache}/kerl
-fi
-ln -s ${cache}/kerl $HOME/.kerl
-kerl install $ver ${ERLROOT} 2>&1 | sed -u 's/^/       /'
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-  echo "-------> Erlang/OTP $ver not cached, building"
-  MAKEFLAGS=-j2 kerl build $ver $ver 2>&1 | sed -u 's/^/       /'
-  if [ ${PIPESTATUS[0]} -ne 0 ]; then
-    echo "-----> Build failed building OTP"
-    exit 1
-  fi
-  kerl install $ver ${ERLROOT} 2>&1 | sed -u 's/^/       /'
-  # work around https://github.com/erlware/relx/issues/211
-  rm ${ERLROOT}/releases/*/start_all_example.rel
-fi
-
-cd $build
-
-if [ ! -f "erlang.mk" ]; then
-  echo "-----> Installing erlang.mk from https://github.com/extend/erlang.mk"
-  curl -o erlang.mk https://raw.githubusercontent.com/extend/erlang.mk/master/erlang.mk
 fi
 
 if [ ! -e ${cache}/bin/wget ] ; then
-  echo "-----> wget not available, building to cache"
-  curl http://ftp.gnu.org/gnu/wget/wget-1.15.tar.gz | tar -xzf - -C /tmp/wget/ --strip-components=1
+  echo "-----> wget not installed"
   WORK_DIR=$(pwd)
-  cd /tmp/wget/
-  ./configure --with-ssl=openssl | sed -u 's/^/       /'
-  make | sed -u 's/^/       /'
+  WGET_BUILD_DIR=$(mktemp -d)
+  cd  $WGET_BUILD_DIR
+  echo "-------> downloading wget"
+  curl --silent http://ftp.gnu.org/gnu/wget/wget-1.15.tar.gz | tar -xzf - --strip-components=1
+  echo "-------> configuring wget"
+  ./configure --with-ssl=openssl >/dev/null |& sed -u 's/^/       /'
+  echo "-------> building wget"
+  make >/dev/null |& sed -u 's/^/       /'
+  echo "-------> installing wget"
   mv ./src/wget ${cache}/bin/wget
   cd $WORK_DIR
 fi
 
-echo "-----> Building with erlang.mk"
-export OTPROOT=${ERLROOT}
-unset GIT_DIR
-PATH=$PATH:${cache}/bin/ make 2>&1 | sed -u 's/^/       /'
-echo
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-  echo "-----> Build failed"
-  ls -l $ERLROOT
-  exit 1
+if [ ! -e ${cache}/bin/kerl ] ; then
+  echo "-----> installing kerl from https://githubusercontent.com/spawngrid/kerl"
+  curl -s -o ${cache}/bin/kerl https://raw.githubusercontent.com/spawngrid/kerl/master/kerl |& sed -u 's/^/       /'
+  chmod +x ${cache}/bin/kerl
 fi
+ln -s ${cache}/kerl $HOME/.kerl
+
+echo "-----> Installing Erlang/OTP ${OTP_VERSION}"
+kerl install ${OTP_VERSION} ${ERLROOT} |& sed -u 's/^/       /'
+if [ ${PIPESTATUS[0]} -ne 0 ]; then
+  echo "-------> Erlang/OTP ${OTP_VERSION} not cached, building"
+  MAKEFLAGS=-j2 kerl build ${OTP_VERSION} ${OTP_VERSION} |& sed -u 's/^/       /'
+  kerl install ${OTP_VERSION} ${ERLROOT} |& sed -u 's/^/       /'
+  # work around https://github.com/erlware/relx/issues/211
+  rm ${ERLROOT}/releases/*/start_all_example.rel
+fi
+
+echo "-----> Building with erlang.mk"
+make |& sed -u 's/^/       /'
+echo
 
 if [ ! -f ./Procfile ]; then
   APP=$(ls ./_rel/)
